<?php

?>


<p>Are you sure that you want to delete customer <b><?php echo $this->escape($this->customer['email']); ?></b> ?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="customer_id" value="<?php echo $this->customer['customer_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
