<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/">[HOME]</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Product <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/product">All</a></li>
                            <li><a href="/product/women-s">Women's</a></li>
                            <li><a href="/product/men-s">Men's</a></li>
                        </ul>
                    </li>
                </ul>
                <?php
                if (!isset($this->sess->customer_email)) {
                    ?>
                    <ul class="nav">
                        <li><a class="fancybox" href="#multistep-register">Multistep Register</a></li> / <li><a class="fancybox" href="#register">Single Register</a></li>
                    </ul>
                    <ul class="nav">
                        <li><a class="fancybox" href="#login">Login</a></li>
                    </ul>
                <?php
                } else {
                    ?>
                    <ul class="nav">
                        <li><a class="fancybox" href="/customer">My Account</a></li>
                    </ul>
                    <ul class="nav">
                        <li><a class="fancybox" href="/customer/logout">Logout</a></li>
                    </ul>
                <?php
                }
                ?>
                <form class="navbar-form form-search pull-right" id="search_form" enctype="application/x-www-form-urlencoded" method="post" action="/search">
                    <input type="hidden" name="id" value="0" id="id" />
                    <input id="name" name="name" type="text" value="<?php if (isset($_POST['name'])) echo $_POST['name']?>" placeholder="type text to search for" class="input-medium search-query">
                    <button type="submit" class="btn">Search</button>
                </form>
            </div>
        </div>
    </div>
</div>