<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('checkinthings.com');
    echo $this->doctype();
    echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
</head>
<body>
<div id="content">
    <h1><?php
            if ($this->breadcrumb) {

                foreach ($this->breadcrumb as $breadcrumb) {
                    foreach ($breadcrumb as $text => $link) {
                        $arBreadCrumb[] = "<a href=\"".$link."\">$text</a>";
                    }
                }

                $arBreadCrumb[] = $this->escape($this->title);

                echo implode(" > ", $arBreadCrumb);

            } else if ($this->title != 'Admin') {
                echo "<a href='/'>Admin</a> > ".$this->escape($this->title);

            } else {
                echo $this->escape($this->title);
            }
        ?></h1>
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>
