<?php
    $this->title = "Admin";
    $this->headTitle($this->title);
?>
<table width="100%" align="center">
    <tr><td height="10" colspan="2"></td></tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff">|&nbsp;&nbsp;<a href="/category">Category</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="/customer">Customer</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="/product">Product</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="/track">Track</a>&nbsp;&nbsp;|</td>
        <td width="50%" align="center" bgcolor="#ffffff"</td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#ffffff"></td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#ffffff"></td>
    </tr>
    <tr><td height="10" colspan="2"></td></tr>
</table>
