<?php
    $this->title = "Product - Delete";
    $this->headTitle($this->title);
?>

<p>Are you sure that you want to delete
    '<?php echo $this->escape($this->product['name']); ?>'
    '<?php echo $this->escape($this->product['description']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="product_id" value="<?php echo $this->product['product_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
