<?
    $this->title = "Product - Feed";
    $this->headTitle($this->title);

    if ($this->arProducts)
    foreach ($this->arProducts as $id => $product) {
        echo "<table>";
        echo "<tr>";
        echo "<td colspan='100'><b>($id)</b></td>";
        echo "</tr>";

        foreach ($product as $key => $value) {
            if (strlen($value) > 120) {
                $value = mb_substr($value, 0, 120)."...";
            }

            echo "<tr>";
            echo "<td>$key:</td><td>$value</td>";
            echo "</tr>";
        }

        echo "<tr>";
        echo "<td colspan='100' height='25'></td>";
        echo "</tr>";

        echo "</table>";
    }
?>