<?php

?>
<table width="100%" align="center">
    <tr><td height="10" colspan="2"></td></tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff">|&nbsp;&nbsp;<a href="<?php echo $this->url(array('controller'=>'product','action'=>'index'));?>">Refresh</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?php echo $this->url(array('controller'=>'product','action'=>'create'));?>">Create</a>&nbsp;&nbsp;|</td>
        <td width="50%" align="center" bgcolor="#eeeeee"><a href="/product/feed/code/tradedoubler">Tradedoubler</a></td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#eeeeee"><a href="/product/feed/code/amazon">Amazon</a></td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#eeeeee"><a href="/product/feed/code/svpply">Svpply</a></td>
    </tr>
    <tr><td height="10" colspan="2"></td></tr>
</table>

<table>
    <tr>
        <th class="crud_title">Action</th>
        <th class="crud_title">ProductId</th>
        <th class="crud_title">Feed</th>
        <th class="crud_title">Channel</th>
        <th class="crud_title">MainCategory</th>
        <th class="crud_title">Name</th>
        <th class="crud_title">ImageUrl</th>
        <th class="crud_title">Active</th>
        <th class="crud_title">LastUpdated</th>
    </tr>
    <?php
        if ($this->products)
        foreach($this->products as $product) {

            $file = $this->config['alfa']['host']."/img/product/".$product['product_id'].".jpg";
            $file_headers = @get_headers($file);

            if (strstr($_SERVER['HTTP_HOST'], "localhost") && strstr($file_headers[0], "200")) {
                $product->image_url = $file;
            }
    ?>
        <tr>
            <td align="center">
                <a href="<?php echo $this->url(array('controller'=>'product','action'=>'update', 'id'=>$product->product_id));?>"><img title="Update" border="0" width="18" height="18" src="/img/icon_update.png"></a>
                <a href="<?php echo $this->url(array('controller'=>'product','action'=>'delete', 'id'=>$product->product_id));?>"><img title="Delete" border="0" width="18" height="18" src="/img/icon_delete.png"></a>
            </td>
            <td align="center"><?php echo $this->escape($product->product_id);?></td>
            <td><?php echo $this->escape($product->feed);?></td>
            <td><?php echo $this->escape($product->channel);?></td>
            <td><?php echo $this->escape($product->main_category);?></td>
            <td><?php echo $this->escape($product->name);?></td>
            <td align="center"><img width="100" height="75" src="<?php echo $this->escape($product->image_url);?>"></td>
            <td align="center"><?php echo $this->escape($product->active);?></td>
            <td><?php echo $this->escape($product->last_updated);?></td>
        </tr>
    <?php } ?>
</table>
