<?php

?>


<p>Are you sure that you want to delete track <b><?php echo $this->escape($this->track['email']); ?></b> ?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="track_id" value="<?php echo $this->track['track_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
