<?php

?>
<table width="100%" align="center">
    <tr><td height="10" colspan="2"></td></tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff">| <a href="<?php echo $this->url(array('controller'=>'track','action'=>'index'));?>">Refresh</a> | <a href="<?php echo $this->url(array('controller'=>'track','action'=>'create'));?>">Create</a> | </td>
        <td width="50%" align="center" bgcolor="#ffffff"</td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#ffffff"></td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#ffffff"></td>
    </tr>
    <tr><td height="10" colspan="2"></td></tr>
</table>

<table>
    <tr>
        <th class="crud_title">Action</th>
        <th class="crud_title">TrackId</th>
        <th class="crud_title">Event</th>
        <th class="crud_title">Link</th>
        <th class="crud_title">HttpReferer</th>
        <th class="crud_title">UserAgent</th>
        <th class="crud_title">RemoteAddr</th>
        <th class="crud_title">LastUpdated</th>
    </tr>
    <?php
        if ($this->tracks)
        foreach($this->tracks as $track) {
    ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'track','action'=>'update', 'id'=>$track->track_id));?>"><img title="Update" border="0" width="18" height="18" src="/img/icon_update.png"></a>
                <a href="<?php echo $this->url(array('controller'=>'track','action'=>'delete', 'id'=>$track->track_id));?>"><img title="Delete" border="0" width="18" height="18" src="/img/icon_delete.png"></a>
            </td>
            <td align="center"><?php echo $this->escape($track->track_id);?></td>
            <td><?php echo $this->escape($track->event);?></td>
            <td><?php echo $this->escape($track->link);?></td>
            <td><?php echo $this->escape($track->http_referer);?></td>
            <td><?php echo $this->escape($track->user_agent);?></td>
            <td><?php echo $this->escape($track->remote_addr);?></td>
            <td><?php echo $this->escape($track->last_updated);?></td>
        </tr>
    <?php } ?>
</table>
