INSERT INTO product (`product_id`, `feed`, `name`) VALUES (NULL, 'tradedoubler', '59 € en vez de 400 € por 5 sesiones de LPG y masaje manual adelgazante, o 79 € en vez de 800 € por 10. ¡Empieza ya la operación bikini!');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'product_url', 'http://pdt.tradedoubler.com/click?a(1540587)p(189599)prod(1076414213)ttid(5)url(http%3A%2F%2Fwww.groupon.es%2Fdeals%2Fsegovia%2Fquiroterapia-manual-adelgazante-reductor-adelgazar%2F4797507%3FCID%3DES_AFF_166_10_1_1)');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'image_url', 'http://static.es.groupon-content.net/37/55/1333976095537.jpg');
UPDATE product SET `description` = 'Opción A: bono de 5 sesiones de LPG con masaje manual adelgazante (59 € en vez 400 €, dto. 85%) Opción B: bono de 10 sesiones de LPG con masaje manual adelgazante (79 € en vez 800 €, dto. 90%) El sistema LPG consiste en un masaje intenso del panículo adiposo mediante rodillos y aspiración de la superficie cutánea Favorece la eliminación de la celulitis y la grasa localizada ayudando así a la reducció' WHERE product_id = 1;
UPDATE product SET `price` = '59.00' WHERE product_id = 1;
UPDATE product SET `currency` = 'EUR' WHERE product_id = 1;
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 't_d_product_id', '1076414213');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 't_d_category_i_d', '1');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 't_d_category_name', 'Categorías');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'merchant_category_name', 'BEAUTY');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'program_name', 'GroupOn');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'program_logo_path', 'http://hst.tradedoubler.com/file/189599/Groupon_flash_logo1.png');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'program_id', '189599');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'advertiser_product_url', 'http://www.groupon.es/deals/segovia/quiroterapia-manual-adelgazante-reductor-adelgazar/4797507?CID=ES_AFF_166_10_1_1');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_country_id', '5');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_facebook_group', '312882927938');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_id', '3073');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_latitude', '40.949');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_longitude', '-4.119');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_name', 'Segovia');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_status', '0');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_top_city', 'false');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_twitter_account', 'Groupon_Madrid');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'city_url', 'segovia');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'conditions', 'Previa cita (95 465 91 25). Cancelaciones con 24 h de antelación. Un cupón por persona . Puedes regalar todos los que quieras. Tienes 6 meses para canjear tu cupón. Se aplican las condiciones generales.');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'country_currency', 'EUR');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'country_id', '5');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'country_shortname', 'ES');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'country_url', 'http://www.groupon.es');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'coupon_valid_from', '2012-04-11 12:00:00');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'coupon_valid_until', '2012-10-11 12:00:00');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'deal__end__time', '2012-04-10 23:59:59');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'discount_desc', '85 %');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'highlights', 'Opción A: bono de 5 sesiones de LPG con masaje manual adelgazante (59 € en vez 400 €, dto. 85%) Opción B: bono de 10 sesiones de LPG con masaje manual adelgazante (79 € en vez 800 €, dto. 90%) El sistema LPG consiste en un masaje intenso del panículo adiposo mediante rodillos y aspiración de la superficie cutánea Favorece la eliminación de la celulitis y la grasa localizada ayudando así a la reducció');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'limited_quantity', 'true');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'logo_url', 'http://static.es.groupon-content.net/s/cdn4019566455/images/layout/groupon.png');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'maximum_purchase', 'null');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'meta_description', '59 € en vez de 400 € por 5 sesiones de LPG y masaje manual adelgazante, o 79 € en vez de 800 € por 10. ¡Empieza ya la operación bikini!');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'meta_keywords', 'tratamiento-reductor lpg quiroterapia-manual-adelgazante celulitis grasa-localizada korner sevilla');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'meta_title', 'Korner: Ahorra 85% en Segovia');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'min_number_customers', '1');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'original_price', '400.0');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'shipping_amount', '0.0');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'sold_count', '0');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'sold_out', 'false');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'start', '2012-04-10 00:00:00');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'status', 'DEAL_CLOSED_WITH_SUCCESS');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'tax', '9.0');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'tipped', 'false');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'title', '59 € en vez de 400 € por 5 sesiones de LPG con masaje manual adelgazante, o 79 € en vez de 800 € por 10. ¡Empieza ya la operación bikini!');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'title_url', 'quiroterapia-manual-adelgazante-reductor-adelgazar');
INSERT INTO product_eav (`product_eav_id`, `product_id`, `attribute`, `value`) VALUES (NULL, 1, 'type', 'MAIN_DEAL');
