<?php
    $response = json_decode($this->response, true);

    require_once('header.phtml');

    if ($this->utils->url_exists($this->specialOfferLocalImage)) {
        $specialOfferSrc = $this->specialOfferLocalImage;
    } else if ($this->utils->url_exists($this->specialOfferRemoteImage)) {
        $specialOfferSrc = $this->specialOfferRemoteImage;
    } else {
        $specialOfferSrc = "/img/foo.png";
    }
?>

<div class="container">
    <div class="row">
        <div class="span9">
            <div class="hero-unit">
                <table width="600" border="0">
                    <tr>
                        <td width="300" valign="top">
                            <h2 class="">Special<br>Offer</h2>
                            <p class="">Here is the best offer of the<br>month, do not loose it!</p>
                            <p><a href="/product/detail/id/<?php echo $this->specialOfferId?>" class="btn btn-primary btn-large">Learn more »</a></p>
                        </td>
                        <td width="300" align="center">
                            <div class="thumbnail">
                            <p><a href="/product/detail/id/<?php echo $this->specialOfferId?>"><img border="0" src="/image.php?product_id=<?=$this->specialOfferId?>&percent=0.75"></a></p>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>

            <ul class="thumbnails">
                <?php
                $arHits = array();

                if ($response['hits']['hits'])
                    foreach ($response['hits']['hits'] as $hit) {
                        foreach ($hit as $key => $value) {

                            if (isset($hit['_source']['product_id']) && !in_array($hit['_source']['product_id'], $arHits)) {
                                $arHits[] = $hit['_source']['product_id'];

                                $localImg = $this->appIni['alfa']['host']."/img/product/".$hit['_source']['product_id'].".jpg";

                                if ($this->utils->url_exists($localImg)) {
                                    $hit['_source']['image_url'] = $localImg;
                                }

                                ?>
                                <li class="span3">
                                    <div class="thumbnail">
                                        <a href="/product/detail/id/<?php echo $hit['_source']['product_id']?>"><img border="0" width="300" height="200" src="<?php echo $hit['_source']['image_url']?>"></a>
                                        <div class="caption">
                                            <!--<h4><a href="/product/detail/id/<?php echo $hit['_source']['product_id']?>">(<?php echo $hit['_source']['product_id']?>)</a> <?php echo $hit['_source']['main_category']?></h4> <?php echo substr($hit['_source']['name'], 0, 64)?>-->
                                            <h4><a href="/product/detail/id/<?php echo $hit['_source']['product_id']?>"><?php echo wordwrap($hit['_source']['name'], 64)?></a> (<?php echo $hit['_source']['main_category']?>)</h4>
                                            <p><strike><?php echo $hit['_source']['currency']?> <?php echo $hit['_source']['price']*(1.2)?></strike>&nbsp;<?php echo $hit['_source']['currency']?> <?php echo $hit['_source']['price']?></p>
                                            <a class="btn btn-want" href="#wantit" onclick="clickTrack('wantit_<?=$hit['_source']['product_id']?>')">Want it</a>&nbsp;
                                            <a class="btn btn-have" href="#haveit" onclick="clickTrack('haveit_<?=$hit['_source']['product_id']?>')">Have it</a>&nbsp;
                                            <a class="btn btn-buy" target="_blank" href="<?=$hit['_source']['product_url']?>" onclick="clickTrack('buyit_<?=$hit['_source']['product_id']?>')">Buy it</a>
                                        </div>
                                    </div>
                                </li>
                            <?php
                            }
                        }
                    }
                ?>
            </ul>

        </div>
    </div>
</div>

<hr />