<?php

?>

<p>Are you sure that you want to delete category <b><?php echo $this->escape($this->category['name']); ?></b> ?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="category_id" value="<?php echo $this->category['category_id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
