<?php

?>
<table width="100%" align="center">
    <tr><td height="10" colspan="2"></td></tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff">| <a href="<?php echo $this->url(array('controller'=>'category','action'=>'index'));?>">Refresh</a> | <a href="<?php echo $this->url(array('controller'=>'category','action'=>'create'));?>">Create</a> | </td>
        <td width="50%" align="center" bgcolor="#ffffff"</td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#ffffff"></td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#ffffff"></td>
    </tr>
    <tr><td height="10" colspan="2"></td></tr>
</table>

<table>
    <tr>
        <th>Action</th>
        <th>CategoryId</th>
        <th>Name</th>
        <th>Url</th>
        <th>Description</th>
        <th>Parent</th>
        <th>Active</th>
        <th>LastUpdated</th>
    </tr>
    <?php
        if ($this->categorys)
        foreach($this->categorys as $category) {

            $file = $this->config['alfa']['host']."/img/category/".$category['category_id'].".jpg";
            $file_headers = @get_headers($file);

            if (strstr($_SERVER['HTTP_HOST'], "localhost") && strstr($file_headers[0], "200")) {
                $category->image_url = $file;
            }
    ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'category','action'=>'update', 'id'=>$category->category_id));?>">Update</a><br>
                <a href="<?php echo $this->url(array('controller'=>'category','action'=>'delete', 'id'=>$category->category_id));?>">Delete</a>
            </td>
            <td><?php echo $this->escape($category->category_id);?></td>
            <td><?php echo $this->escape($category->name);?></td>
            <td><?php echo $this->escape($category->url);?></td>
            <td><?php echo $this->escape($category->description);?></td>
            <td><?php echo $this->escape($category->parent);?></td>
            <td><?php echo $this->escape($category->active);?></td>
            <td><?php echo $this->escape($category->last_updated);?></td>
        </tr>
    <?php } ?>
</table>
