<?php

?>
<table width="100%" align="center">
    <tr><td height="10" colspan="2"></td></tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff">|&nbsp;&nbsp;<a href="<?php echo $this->url(array('controller'=>'category','action'=>'index'));?>">Refresh</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?php echo $this->url(array('controller'=>'category','action'=>'create'));?>">Create</a>&nbsp;&nbsp;|</td>
        <td width="50%" align="center" bgcolor="#ffffff"</td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#ffffff"></td>
    </tr>
    <tr>
        <td width="50%" align="left" bgcolor="#ffffff"></td>
        <td width="50%" align="center" bgcolor="#ffffff"></td>
    </tr>
    <tr><td height="10" colspan="2"></td></tr>
</table>

<table>
    <tr>
        <th class="crud_title">Action</th>
        <th class="crud_title">CategoryId</th>
        <th class="crud_title">Name</th>
        <th class="crud_title">Url</th>
        <th class="crud_title">Description</th>
        <th class="crud_title">Parent</th>
        <th class="crud_title">Active</th>
        <th class="crud_title">LastUpdated</th>
    </tr>
    <?php
        if ($this->categorys)
        foreach($this->categorys as $category) {

            $file = $this->config['alfa']['host']."/img/category/".$category['category_id'].".jpg";
            $file_headers = @get_headers($file);

            if (strstr($_SERVER['HTTP_HOST'], "localhost") && strstr($file_headers[0], "200")) {
                $category->image_url = $file;
            }
    ?>
        <tr>
            <td align="center">
                <a href="<?php echo $this->url(array('controller'=>'category','action'=>'update', 'id'=>$category->category_id));?>"><img title="Update" border="0" width="18" height="18" src="/img/icon_update.png"></a>
                <a href="<?php echo $this->url(array('controller'=>'category','action'=>'delete', 'id'=>$category->category_id));?>"><img title="Delete" border="0" width="18" height="18" src="/img/icon_delete.png"></a>
            </td>
            <td align="center"><?php echo $this->escape($category->category_id);?></td>
            <td><?php echo $this->escape($category->name);?></td>
            <td><?php echo $this->escape($category->url);?></td>
            <td><?php echo $this->escape($category->description);?></td>
            <td align="center"><?php echo $this->escape($category->parent);?></td>
            <td align="center"><?php echo $this->escape($category->active);?></td>
            <td><?php echo $this->escape($category->last_updated);?></td>
        </tr>
    <?php } ?>
</table>
