<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('checkinthings.com');

    echo $this->doctype();

    echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>

    <!-- Included Bootstrap CSS Files -->
    <link rel="stylesheet" href="/js/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="/js/bootstrap/css/bootstrap-responsive.css" />

    <!-- Includes FontAwesome -->
    <link rel="stylesheet" href="/css/font-awesome/css/font-awesome.css" />

    <!-- Css -->
    <link rel="stylesheet" href="/css/style.css" />

</head>
<body>
<div id="main_content">
    <h1><?php

        if ($this->breadcrumb) {

            foreach ($this->breadcrumb as $breadcrumb) {
                foreach ($breadcrumb as $text => $link) {
                    $arBreadCrumb[] = "<a href='$link'>$text</a>";
                }
            }

            $arBreadCrumb[] = $this->escape($this->title);

            echo implode(" > ", $arBreadCrumb);
        } else if ($this->title != 'Home') {
            echo "<a href='/'>Index</a> > ".$this->escape($this->title);
        } else {
            echo $this->escape($this->title);
        }


        ?></h1>
    <?php echo $this->layout()->content; ?>
</div>

<!-- Js -->
<script src="/js/jquery-1.10.0.min.js"></script>
<script src="/js/jquery.bgstretch/js/jquery.bgstretch.js"></script>
<script src="/js/bootstrap/js/bootstrap.js"></script>
<script src="/js/holder.js"></script>
<script src="/js/script.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $.Bgstretch({image: '/img/background.png'});
    });
</script>

</body>
</html>
