<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('checkinthings.com');

    echo $this->doctype();

    echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>

    <!-- Included Bootstrap CSS Files -->
    <link rel="stylesheet" href="/js/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="/js/bootstrap/css/bootstrap-responsive.css" />

    <!-- Includes FontAwesome -->
    <link rel="stylesheet" href="/css/font-awesome/css/font-awesome.css" />

    <!-- Add fancyBox main JS and CSS files -->
    <link rel="stylesheet" type="text/css" href="/css/fancybox/jquery.fancybox.css?v=2.1.5" media="screen" />

    <!-- Add Button helper (this is optional) -->
    <link rel="stylesheet" type="text/css" href="/css/fancybox/helpers/jquery.fancybox-buttons.css?v=1.0.5" />

    <!-- Add Thumbnail helper (this is optional) -->
    <link rel="stylesheet" type="text/css" href="/css/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />

    <!-- Css -->
    <link rel="stylesheet" href="/css/style.css" />

</head>
<body>
<div id="main_content">
    <h1><?php

        if ($this->breadcrumb) {

            foreach ($this->breadcrumb as $breadcrumb) {
                foreach ($breadcrumb as $text => $link) {
                    $arBreadCrumb[] = "<a href='$link'>$text</a>";
                }
            }

            $arBreadCrumb[] = $this->escape($this->title);

            echo implode(" > ", $arBreadCrumb);
        } else if ($this->title != 'Home') {
            echo "<a href='/'>Index</a> > ".$this->escape($this->title);
        } else {
            echo $this->escape($this->title);
        }


        ?></h1>
    <?php echo $this->layout()->content; ?>
</div>

<div id="login" style="width:400px;display: none;">
    <?php include ("login.phtml"); ?>
</div>

<div id="register" style="width:400px;display: none;">
    <?php include ("register.phtml"); ?>
</div>

<!-- Js -->
<script src="/js/jquery-1.10.0.min.js"></script>
<script src="/js/jquery.mousewheel-3.0.6.pack.js"></script>
<script src="/js/fancybox.js"></script>

<!-- Add fancyBox main JS files -->
<script type="text/javascript" src="/js/fancybox/jquery.fancybox.js?v=2.1.5"></script>

<!-- Add Button helper (this is optional) -->
<script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>

<!-- Add Thumbnail helper (this is optional) -->
<script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>

<!-- Add Media helper (this is optional) -->
<script type="text/javascript" src="/js/fancybox/helpers/jquery.fancybox-media.js?v=1.0.6"></script>

<script src="/js/jquery.bgstretch/js/jquery.bgstretch.js"></script>
<script src="/js/bootstrap/js/bootstrap.js"></script>
<script src="/js/holder.js"></script>
<script src="/js/background.js"></script>
<script src="/js/function.js"></script>

</body>
</html>
