<b>Login</b><br>
<br>
<form name="loginForm" method="post" action="/customer">
    <input type="hidden" name="event" value="login">
    <table>
        <tr>
            <td>email: </td><td colspan="2"><input type="text" name="email"></td>
        </tr>
        <tr>
            <td>password: </td><td><input type="password" name="password"></td><td><input type="submit" value="Send"></td>
        </tr>
    </table>
</form>