<div id="login_form">
    <form name="loginForm" method="post" action="/customer">
    <input type="hidden" name="event" value="login">
        <table width="450">
            <tr>
                <td colspan="2" align="right">
                    <img border="0" src="/img/send.png" onclick="document.loginForm.submit();">
                </td>
            </tr>
            <tr>
                <td><input type="text" id="login_email" name="email"></td><td colspan="2">Your email address.</td>
            </tr>
            <tr>
                <td><input type="password" id="login_password" name="password"></td><td>Your password.</td>
            </tr>
        </table>
</form>
</div>
