<div id="login_form">
    <form name="loginForm" method="post" action="/customer">
    <input type="hidden" name="event" value="login">
        <table width="450">
            <tr>
                <td colspan="2" align="right">
                    <img border="0" src="/img/send.png" onclick="document.loginForm.submit();">
                </td>
            </tr>
            <tr>
                <td><input type="text" id="login_email" name="email"></td><td colspan="2">Your email address.</td>
            </tr>
            <tr>
                <td><input type="password" id="login_password" name="password"></td><td>Your password.</td>
            </tr>
            <tr>
                <td height="50"></td>
            </tr>
            <tr>
                <td>
                    Or login using Facebook<br>
                    <!--
                      Below we include the Login Button social plugin. This button uses the JavaScript SDK to
                      present a graphical Login button that triggers the FB.login() function when clicked.

                      Learn more about options for the login button plugin:
                      /docs/reference/plugins/login/
                    -->
                    <div id="fb-root"></div>
                    <div id="fb_login"><fb:login-button show-faces="true" width="200" max-rows="1"></fb:login-button></div>
                    <br>
                    <div id="fb_logout"></div>
                    <br>
                    <div id="fb_data"></div>
                    <br>
                </td>
            </tr>
        </table>
</form>
</div>
