<div id="multistep">
    <form name="multistepForm" method="post" action="/customer">
    <input type="hidden" name="event" value="multistep">

        <!-- #first_step -->
        <div id="first_step">
            <div class="next_step">
                <input class="submit" name="submit_first" id="submit_first" value=""/>
            </div>
             <table width="675" border="0">
                <tr>
                    <td width="300">
                        <input type="text" name="email" id="email" value="email address" />
                    </td>
                    <td width="375" colspan="2">
                        <label for="email">Your email address. We send important administration notices to this address. </label>
                    </td>
                </tr>
            </table>
        </div>

        <!-- #second_step -->
        <div id="second_step">
            <div class="next_step">
                <input class="submit" name="submit_second" id="submit_second" value="" />
            </div>
            <table width="675" border="0">
                <tr>
                    <td>
                        <input type="password" name="password" id="password" value="password" />
                    </td>
                    <td width="375" colspan="2">
                        <label for="password">At least 4 characters. Use a mix of upper and lowercase for a strong password.</label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="password" name="cpassword" id="cpassword" value="password" />
                    </td>
                    <td width="375" colspan="2">
                        <label for="cpassword">If your passwords aren’t equal, you won’t be able to continue with signup.</label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="text" name="firstname" id="firstname" value="first name" />
                    </td>
                    <td width="375" colspan="2">
                        <label for="firstname">Your First Name. </label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="text" name="lastname" id="lastname" value="last name" />
                    </td>
                    <td width="375" colspan="2">
                        <label for="lastname">Your Last Name. </label>
                    </td>
                </tr>
            </table>
        </div>


        <!-- #third_step -->
        <div id="third_step">
            <div class="next_step">
                <input class="submit" name="submit_third" id="submit_third" value="" />
            </div>
            <table width="675" border="0">
                <tr>
                    <td width="300">
                        <select id="age" name="age">
                            <option> 0 - 17</option>
                            <option>18 - 25</option>
                            <option>26 - 40</option>
                            <option>40+</option>
                        </select>
                    </td>
                    <td width="375" colspan="2">
                        <label for="age">Your age range. </label>
                    </td>
                </tr>

                <tr>
                    <td width="300">
                        <select id="gender" name="gender">
                            <option>Male</option>
                            <option>Female</option>
                        </select>
                    </td>
                    <td width="375" colspan="2">
                        <label for="gender">Your Gender. </label>
                    </td>
                </tr>

                <tr>
                    <td width="300">
                        <select id="country" name="country">
                            <option>United States</option>
                            <option>United Kingdom</option>
                            <option>Canada</option>
                            <option>Serbia</option>
                            <option>Italy</option>
                        </select>
                    </td>
                    <td width="375" colspan="2">
                        <label for="country">Your country. </label>
                    </td>
                </tr>
            </table>
        </div>


        <!-- #fourth_step -->
        <div id="fourth_step">
            <div class="next_step">
                <input class="send submit" type="submit" name="submit_fourth" id="submit_fourth" value="" />
            </div>
            <table width="675" border="0">
                <tr><td>Email</td><td></td></tr>
                <tr><td>Password</td><td></td></tr>
                <tr><td>Name</td><td></td></tr>
                <tr><td>Age</td><td></td></tr>
                <tr><td>Gender</td><td></td></tr>
                <tr><td>Country</td><td></td></tr>
            </table>
        </div>
    </form>
</div>

<div id="progress_bar">
    <div id="progress"></div>
    <div id="progress_text">0% Complete</div>
</div>