<?php
    if ($this->utils->url_exists($this->productALocalImage)) {
        $productASrc = $this->productALocalImage;
    } else if ($this->utils->url_exists($this->productARemoteImage)) {
        $productASrc = $this->productARemoteImage;
    } else {
        $productASrc = "/img/foo.png";
    }

    if ($this->utils->url_exists($this->productBLocalImage)) {
        $productBSrc = $this->productBLocalImage;
    } else if ($this->utils->url_exists($this->productBRemoteImage)) {
        $productBSrc = $this->productBRemoteImage;
    } else {
        $productBSrc = "/img/foo.png";
    }
?>
<div id="play_form">
    <form name="playForm" method="post" action="/">
    <input type="hidden" name="event" value="play">
        <table width="600" align="center">
            <tr>
                <td width="240" height="300">
                    <div id="product_a">
                    <table width="300" background="#dddddd">
                        <tr valign="top">
                            <td align="center" height="250"><img border="0" src="/image.php?product_id=<?=$this->productAId?>&percent=0.5"></td>
                        </tr>
                        <tr valign="top">
                            <td align="center" height="50">
                                <a class="btn btn-play" onclick="playTrack('sexyit_<?=$this->productAId?>', 'b')">Sexy it</a>
                            </td>
                        </tr>
                    </table>
                    </div>
                </td>
                <td width="20" height="300">

                </td>
                <td width="240" height="300">
                    <div id="product_b">
                    <table width="300" background="#dddddd">
                        <tr valign="top">
                            <td align="center" height="250"><img border="0" src="/image.php?product_id=<?=$this->productBId?>&percent=0.5"></td>
                        </tr>
                        <tr valign="top">
                            <td align="center" height="50">
                                <a class="btn btn-play" onclick="playTrack('sexyit_<?=$this->productBId?>', 'a')">Sexy it</a>
                            </td>
                        </tr>
                    </table>
                    </div>
                </td>
            </tr>
        </table>
</form>
</div>
