<?php

    $response = json_decode($this->response, true);

    require_once('header.phtml');

    $this->customer = json_decode($this->customer, true);

    if (isset($this->customer['engine_wants'])) $wants = explode(",", $this->customer['engine_wants']);
    if (isset($this->customer['engine_haves'])) $haves = explode(",", $this->customer['engine_haves']);
    if (isset($this->customer['engine_buys'])) $buys = explode(",", $this->customer['engine_buys']);
?>

<div class="container">
    <div class="message">
    <?php
        if ($this->success) {
            echo "<span class=\"success-message\">".$this->success."</span>";
        } else if ($this->error) {
            echo "<span class=\"error-message\">".$this->error."</span>";
        }
    ?>
    </div>
    <div class="body">
    <?php
        if ($this->sess->customer_email) {
    ?>
        <table>
            <tr>
                <td height="15" colspan="10"></td>
            </tr>
            <tr>
                <td>Firstname:</td><td><?=$this->sess->customer_firstname?></td>
            </tr>
            <tr>
                <td>Lastname:</td><td><?=$this->sess->customer_lastname?></td>
            </tr>
            <tr>
                <td>Email:</td><td><?=$this->sess->customer_email?></td>
            </tr>
        </table>
        <hr>
        <table>
            <tr>
                <td colspan="10">Wants</td>
            </tr>
            <tr>
                <?php
                    if (isset($wants))
                    foreach ($wants as $productId) {
                        echo "<td><a href=\"/product/detail/id/".$productId."\"><img border=\"0\" src=\"image.php?product_id=".$productId."\"></a></td>";
                    }
                ?>
            </tr>
        </table>
        <hr>
        <table>
            <tr>
                <td>Haves</td>
            </tr>
            <tr>
                <?php
                if (isset($haves))
                foreach ($haves as $productId) {
                    echo "<td><a href=\"/product/detail/id/".$productId."\"><img border=\"0\" src=\"image.php?product_id=".$productId."\"></a></td>";
                }
                ?>
            </tr>
        </table>
        <hr>
        <table>
            <tr>
                <td>Buys</td>
            </tr>
            <tr>
                <?php
                if (isset($buys))
                foreach ($buys as $productId) {
                    echo "<td><a href=\"/product/detail/id/".$productId."\"><img border=\"0\" src=\"image.php?product_id=".$productId."\"></a></td>";
                }
                ?>
            </tr>
        </table>
    <?php
        }
    ?>
    </div>
</div>
<br>
<div id="fb_logout"></div>
<br>
<div id="fb_data"></div>
<br>