<?php

    $response = json_decode($this->response, true);

    require_once('header.phtml');

?>

<div class="container">
    <div class="message">
    <?php
        if ($this->success) {
            echo "<span class=\"success-message\">".$this->success."</span>";
        } else if ($this->error) {
            echo "<span class=\"error-message\">".$this->error."</span>";
        }
    ?>
    </div>
    <div class="body">
    <?php
        if ($this->sess->customer_email) {
    ?>
        <table>
            <tr>
                <td height="15" colspan="10"></td>
            </tr>
            <tr>
                <td>Firstname:</td><td><?=$this->sess->customer_firstname?></td>
            </tr>
            <tr>
                <td>Lastname:</td><td><?=$this->sess->customer_lastname?></td>
            </tr>
            <tr>
                <td>Email:</td><td><?=$this->sess->customer_email?></td>
            </tr>
        </table>
        <hr>
        <table>
            <tr>
                <td>Wants</td>
            </tr>
        </table>
        <hr>
        <table>
            <tr>
                <td>Haves</td>
            </tr>
        </table>
        <hr>
        <table>
            <tr>
                <td>Buys</td>
            </tr>
        </table>
    <?php
        }
    ?>
    </div>
</div>
