<?php

    $response = json_decode($this->response, true);

    require_once('header.phtml');

?>
<div class="container">
    <div class="message">
        <?php
        if ($this->success) {
            echo "<span class=\"success-message\">".$this->success."</span>";
        } else if ($this->error) {
            echo "<span class=\"error-message\">".$this->error."</span>";
        }
        ?>
    </div>
</div>
